language: java
sudo: false

addons:
  sonarcloud:
    organization: retest
    token:
      secure: "${SONAR_CLOUD_TOKEN}"

notifications:
  email: false

cache:
  directories:
    - "${HOME}/.sonar/cache/"
    - "${HOME}/.m2/"

install: true

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar

before_deploy:
  - mvn package -DskipTests -P deb,docker

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file:
    - "./target/rebazer-*.jar"
    - "./target/rebazer-*.deb"
  skip_cleanup: true
  on:
    tags: true
