language: java
dist: trusty

git:
  depth: false

addons:
  sonarcloud:
    organization: retest
    token:
      secure: "${SONAR_CLOUD_TOKEN}"

notifications:
  email: false

cache:
  directories:
    - "${HOME}/.sonar/cache/"
    - "${HOME}/.m2/"

services:
  - docker

install: true

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -P deb

deploy:
  - provider: releases
    api_key: "${GH_TOKEN}"
    file_glob: true
    file:
      - "./target/rebazer-*.jar"
      - "./target/rebazer-*.deb"
    skip_cleanup: true
    on:
      tags: true

  - provider: script
    script: mvn jib:build -Djib.to.auth.username=${DOCKER_USERNAME} -Djib.to.auth.password=${DOCKER_PASSWORD}
    skip_cleanup: true
    on:
      tags: true
